theme: jekyll-theme-tactile
title: <p style="align=center">Parker L. Brody</p>
description: <span style="font-variant:small-caps;">Morphology | Computational Linguistics | Historical Linguistics</span>
