theme: jekyll-theme-tactile
title: <p style="text-align: center;"> <span style="font-variant:small-caps;">Parker L. Brody</span> </p>
description: <p style="text-align: center;"> <span style="font-variant:small-caps;">Morphology | Computational Linguistics | Historical Linguistics</span> </p>
