theme: jekyll-theme-tactile
title: <span style="font-variant:small-caps;text-align: center">Parker L. Brody</span>
description: <span style="font-variant:small-caps;text-align: center">Morphology | Computational Linguistics | Historical Linguistics</span>
