theme: jekyll-theme-tactile
title: <span style="font-variant:small-caps;">Parker L. Brody</span>
description: <span style="font-variant:small-caps;">Morphology | Computational Linguistics | Historical Linguistics</span>
